export const AUTH_SUCCESS_MESSAGE='AUTH_SUCCESS_MESSAGE';

export const AUTH_FAILURE_MESSAGE='AUTH_FAILURE_MESSAGE';

export const AUTH_USER_SIGN_IN_SUCCESSFUL="AUTH_USER_SIGN_IN_SUCCESSFUL"

export const AUTH_USER_STAY_UP="AUTH_USER_STAY_UP"

export const LOAD_SEARCH_MOVIES="LOAD_SEARCH_MOVIES";

export const LOG_OUT="LOG_OUT"

export const GET_MY_FAVORITES="GET_MY_FAVORITES"

export const STAY_UP_FAV_MOVIES='STAY_UP_FAV_MOVIES';

export const NEW_LIST_AFTER_DELETION = 'NEW_LIST_AFTER_DELETION';

export const ADD_TO_FAV='ADD_TO_FAV'
// export const AUTH_