export const AUTH_SUCCESS_MESSAGE='AUTH_SUCCESS_MESSAGE';

export const AUTH_FAILURE_MESSAGE='AUTH_FAILURE_MESSAGE';

export const AUTH_USER_SIGN_IN_SUCCESSFUL="AUTH_USER_SIGN_IN_SUCCESSFUL"

export const AUTH_USER_STAY_UP="AUTH_USER_STAY_UP"

// export const AUTH_